# Generated by Django 4.2.6 on 2023-11-03 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
