# Generated by Django 4.2.6 on 2023-11-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0002_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
